mtth/avsc

lib/types.js
test/test_types.js

The constructors for schema defined errors now call `Error.captureStackTrace`
if it is available. As of today `Error.captureStackTrace` is only
available in V8 environments (nodejs & Chrome).

call `Error.captureStackTrace` if possible

---

lib/specs.js

This gets the tests passing on windows, and should only affect people on that.
I'd think that regex checks would be better, since JSON and IDL are pretty unambiguous (though hardly trivial), but I suppose you *could* name a file `{"type": "fixed", "size": 100}` in Linux :)

Windows compat: use path.sep instead of '/' in gereric parse().

---

package.json
types/index.d.ts

These are probably wrong and/or incomplete. They may serve as a starter though.

Add (incomplete) Typescript definitions

---

package.json

Currently, `tsc --strict` warns for projects with a dependency on
the latest avsc (5.1.2) due to the folder types/ not being included in the
published package.

Add the `types/` folder to the published NPM package

---

types/index.d.ts

Many of the types were generated by (a patched version of) dts-gen.
Because of that, many methods are vague and say `any`.
Rearrange the layout of the declarations to match what dts-gen emitted
(By dts-gen's design, this should match with the signature of `require('avsc')`)
- Keep the precise annotations that were already made, moving some.
- Make interfaces into classes where they correspond to an actual JS
class (i.e. has function and function prototype)
A TODO was added to make places using types of `any` specific later.
I'm not familiar enough with this project to be certain of the intent,
and adding the methods/classes is a large enough PR on its own.
Add types/ folder to the package for `tsc`.
- This is necessary for that folder to be included in the package
published to NPM
The …

Add more details to typescript annotation file, rearrange it.

---

lib/types.js
test/test_types.js

Because the resolver creates cpde that uses field names as variables you get an error if you use a javascript keyword as a record field name when creating a resolver:
```
SyntaxError: Unexpected token void
at new Function (<anonymous>)
at RecordType._update (/code/node_modules/avsc/lib/types.js:2385:20)
at RecordType.Type.createResolver (/code/node_modules/avsc/lib/types.js:523:10)
at RecordType._update (/code/node_modules/avsc/lib/types.js:2334:30)
at RecordType.Type.createResolver (/code/node_modules/avsc/lib/types.js:523:10)
```
Fix is a little lazy, but it works and it'd make field names starting with numbers work too. I considered making an object to store the data but that might affect performance.

Fix creating a resolver when a record field name is a javascript keyword

---

types/index.d.ts

Seen in a typescript project using avsc:
(And using --strict)
```
node_modules/avsc/types/index.d.ts(72,3): error TS7010: '_skip', which
lacks return-type annotation, implicitly has an 'any' return type.
```

Fix line causing an error in typescript 2.7.2

---

types/index.d.ts

Hi,
I took the liberty to update the typescript definitions. They were not working for me, so I corrected them as far as I could. 
I tried to use generics on the types, but reverted those changes for now as these become awkward with the field definitions in the types (not sure how to create an array of generic field types, where the generic parameter is not set yet...).
There may be more TODOs but, I think this one is an improvement...
Regards,
Joost

Update of typescript definitions

---

lib/containers.js

I am decoding some avro files in my app and noticed that some of the files would hang forever when decoding...the `BlockDecoder` would never emit the `end` event.  I tried to reproduce the issue with some tests, but wasn't able to generate an avro file that demonstrated the behavior other than some large avro files I can't share here unfortunately.  I am not a fan of doing pull requests without tests, but was unable to build a test.  The issue is at the end of my decoding I saw this when I added `console.log(data)` to line `277` of `lib/containers.js`:
```
BlockData { index: 134, buf: <Buffer >, cb: [Function: chunkCb], count: 0 }
```
The above data block is the last block received.  There might be something invalid or missing in the file...I'm not sure, but when that data block is …

Fix hang on empty block

---

types/index.d.ts

These were `TODO` so I had a go at adding them as it
was casuing some ugliness when I used avsc from Typescript.
These seem to be correct, and definitely work for me, but it
would be great if someone more familar with the codebase
could check my work :-)
It would have been nice to also constrain the type of
streams further depending on whether the transport would
be read, write, or duplex. I had a quick look at this but
it turned out to be a larger change so I decided to back
off and go with a smaller diff.

Add type defs for TransportFunction

---

lib/specs.js
package-lock.json
package.json
test/dat/Hello.avdl
test/test_specs.js

I realized that the package does not support Avro 1.9.0 Specification yet, but I wanted to open up this PR to allow the parsing of files to not error at the very least when it sees default values for enums. https://avro.apache.org/docs/current/spec.html#Enums.
At a minimum, this will allow the parsing of a file to continue without a failure because of an unrecognized token. If you wish to add the ability to recognize and use the default value, it will take a little bit more time on my end.

Allow idl files to recognize default values on enums

---

types/index.d.ts

Hi, I've started migrating my project from JS to TS and got an error due to the fact that the type declaration for `typeHook` option does not accept returning `undefined` values.
According to https://github.com/mtth/avsc/blob/f69d61cdeddaee7ba16b9126e0bcf8eaf0a77026/lib/types.js#L154, returning `undefined` should be fine: code behaves as if the `typeHook` was not provided for that specific type we are going through.

ForSchemaOptions.typeHook should accept undefined

---

lib/types.js
test/test_types.js

The Avro spec does not restrict the fixed type to have at least 1 byte of length
in fact: the binary encoding ist designed to omit a zero length field completely
using the schema this allows one to annotate types with static information which doesn not have to travel across the wire

permit zero length fixed type as specified by avro

---

lib/utils.js

Add convenience alias for util.format

---

lib/types.js

We benchmarked this on internal types with arrays of longer lengths and it brought us ~10% improvement on internal benchmarks.
Note: This creates "holey" arrays in V8 but this seems to have negligible performance impact on the array access speed, presumably JIT or CPU learn to default branch in branch prediction
Sample run:
old:
fromBuffer      | toBuffer      | isValid       | (ops/sec)
---------:      | -------:      | ------:       | ---------
19,109,491      | 5,040,556     | 69,815,976    | ArrayInt.avsc
1,137,653       | 892,341       | 64,718,404    | ArrayString.avsc
new:
fromBuffer      | toBuffer      | isValid       | (ops/sec)
---------:      | -------:      | ------:       | ---------
21,969,180      | 5,099,055     | 70,740,014    | ArrayInt.avsc
1,233,871       | 891,253 …

Performance improvements to ArrayType.

---

types/index.d.ts

Without this, code like the following will fail to compile with `strictNullChecks` on: 
```ts
import avsc from 'avsc'
import crc32 from 'buffer-crc32'
import snappy from 'snappy'
export const encodeAvro = (schema: avsc.Schema) =>
new avsc.streams.BlockEncoder(schema, {
writeHeader: 'auto',
codec: 'snappy',
codecs: {
snappy: (buf, cb) => {
const checksum = crc32(buf)
snappy.compress(buf, (err, deflated) => {
if (err) {
return cb(err) // <---
}
const block = Buffer.alloc(deflated.length + 4)
deflated.copy(block)
checksum.copy(block, deflated.length)
cb(null, block)
})
}
}
})
```
The compiler will complain that no argument is given for `value` in `cb(err)`.
Example from a callback type in `@types/node` for reference: `type TransformCallback = (error?: Error | null, data?: any) => void;`

Callback type: Make value optional, make error nullable

---

types/index.d.ts

`extractFileHeader` returns header but in types description it returns `void`. 
That cause some Type Script errors when the function is used.
<details>
<summary>Actual `extractFileHeader` behavior code</summary>
```javascript
function extractFileHeader(path, opts) {
opts = opts || {};
var decode = opts.decode === undefined ? true : !!opts.decode;
var size = Math.max(opts.size || 4096, 4);
var buf = utils.newBuffer(size);
var fd = fs.openSync(path, 'r');
try {
var pos = fs.readSync(fd, buf, 0, size);
if (pos < 4 || !containers.MAGIC_BYTES.equals(buf.slice(0, 4))) {
return null;
}
var tap = new utils.Tap(buf);
var header = null;
do {
header = containers.HEADER_TYPE._read(tap);
} while (!isValid());
if (decode !== false) {
var meta = header.meta;
meta['avro.schema'] = …
```

Fix `extractFileHeader` return type

---

package-lock.json
package.json
types/index.d.ts

Looks like type definition update was missed when https://github.com/mtth/avsc/pull/261 change was submitted.
Added default value for enum type definition

Minor type definition update

---

etc/browser/lib/crypto.js
lib/containers.js
lib/index.js
lib/services.js
lib/types.js
lib/utils.js
test/test_containers.js
test/test_index.js
test/test_types.js

Add buffer import to simplify browser builds

---

etc/browser/avsc-services.js
etc/browser/lib/files.js
lib/files.js
lib/specs.js
test/test_specs.js
types/index.d.ts

First off, apologies for leaving you hanging for a year! Some stuff came up and this fell off my radar for a while, and this seemed like it was going to be more fiddly and difficult than it ended up being.
This import hook API isolates all platform-specific path resolution stuff within the import hook itself. The hook now takes the path of the imported file *and* the path of the file that imported it, and calls the callback with the file contents, and the *resolved* path of the imported file. That second part is what stumped me on my last attempt.
I also started work last year on a "de-Buffer-ification" branch, but ran into some performance cliffs. I finally figured those out (except for TextEncoder/TextDecoder, which is still slower in Node sadly), and the code [is now on …

Refactor import hook API to subsume all platform-dependent behavior

---

.github/workflows/ci.yml

Reasoning:
* Current is 22
* Active is 20
* Maintenance is 18
Any odd-numbered releases and older than 18 are unsupported.
We could possibly add 23 if we wanted to be thorough, but sticking to LTS versions is probably okay.
From https://nodejs.org/en/about/previous-releases on 2024-09-11.
We should probably also update https://github.com/mtth/avsc/blob/7cb76a6eb7b0d5b5a71c9cfb446acf3eff763006/package.json#L43
Node 6 was released on 26 Apr 2016, over 8 years ago.

chore: update node version matrix

---

etc/scripts/perf

Seems like avro.parse was removed in https://github.com/mtth/avsc/pull/428.

Fix perf script

---

etc/benchmarks/avro-serialization-implementations/scripts/decode/node-avro-io.js
etc/benchmarks/avro-serialization-implementations/scripts/encode/node-avro-io.js
etc/benchmarks/avro-serialization-implementations/scripts/encode/node-etp-avro.js
etc/benchmarks/js-serialization-libraries/index.js
etc/browser/avsc.js
etc/browser/lib/md5.js
etc/schemas/Float.avsc
etc/scripts/infer
etc/scripts/meta
etc/scripts/perf
lib/containers.js
lib/index.js
lib/platform.js
lib/types.js
lib/utils.js
package.json
test/test_containers.js
test/test_index.js
test/test_types.js
test/test_utils.js

I still need to do some cleanups and replace uses of `Buffer.compare`, but I'm putting this PR here so you can benchmark it. Before I can complete this, #428 (minus the version bump) should be merged in, as the services code uses `Buffer` everywhere and expects fixed/bytes types to decode to `Buffer`s.
I've made some tweaks to the benchmarking setup, so comparing this directly to the master branch won't work:
- I've added an `ArrayFloat` benchmark to go along with `ArrayDouble`.
- I use the `--expose-gc` flag when benchmarking in order to manually trigger garbage collection between benches, hopefully making results more consistent.
- I've changed the length distribution of strings to be exponentially weighted, so shorter strings are still *likely* but longer strings will now be …

Replace Buffer with Uint8Array

---

types/index.d.ts

`typeHook` is called for an unknown named type, e.g. `{ type: "record", name: "ns.MyName" }` yields `typeHook("ns.MyName", ...`
via https://github.com/mtth/avsc/issues/468#issuecomment-2357448344

fix: `typeHook` can receive `string`

---

.github/workflows/ci.yml

see https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

ci: use checkouts v4

---

test/test_types.js

via https://github.com/mtth/avsc/pull/469#issuecomment-2357428899

test: add test for synthetic constructor

---

etc/browser/avsc.js

Seems like these were removed in #428.

Re-add types exports for browser

---

lib/types.js
test/test_types.js
types/index.d.ts

The Avro specification defines:
> Unions may not contain more than one schema with the same type, except for the named types record, fixed and enum
see https://avro.apache.org/docs/1.11.1/specification/#unions
meaning that if a `record` type has a name, it is valid to mix multiple of them in a union, unwrapped.
The same change should possibly be made for enums as well.

feat: allow named types in unions

---

etc/browser/lib/platform.js
lib/platform.js
lib/types.js

As discussed #483, `util` package does not support in browser env without proper bundler setup.

fix: process is not defined in browser env

---

lib/types.js

Was broken via #469.
Without this fix, the error message is `undefined`:

fix(UnwrappedUnionType): `this` reference

---

types/index.d.ts

Via:
> is it safe to assume that all occurrences of Buffer should become Uint8Array
Yes.
_Originally posted by @mtth in https://github.com/mtth/avsc/issues/452#issuecomment-2409033315_

fix(types): `Buffer` -> `Uint8Array`

---

types/index.d.ts

The `random()` method on a type generates a random _value_ conforming to the type of the schema. The TypeScript type definitions for this method were incorrect - they claimed that this method returned the type object itself. For instance, calling random on a `BooleanType` returns a `boolean`, not a `BooleanType`. I assume this has gone undetected for years, because this method is rarely used.
Because the types for schemas do not carry complex type information in generics, many of these return types are rather imprecise. I have had to resort to `unknown` quite often, because more exact types are not available. I have chose `unknown` over `any`, to maintain type safety.

Fix return type annotations for the random() method
